/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hernandez
 */
public class FormEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FormEmpleado
     */
    public FormEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstadoC = new javax.swing.ButtonGroup();
        groupGener = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        NameEdad = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        NameID1 = new javax.swing.JLabel();
        NameNombre = new javax.swing.JLabel();
        NameApellido = new javax.swing.JLabel();
        NameCedula = new javax.swing.JLabel();
        NameEstadoC = new javax.swing.JLabel();
        NameGenero = new javax.swing.JLabel();
        rdCasado = new javax.swing.JRadioButton();
        rdSoltero = new javax.swing.JRadioButton();
        rdMasculino = new javax.swing.JRadioButton();
        rdFemenino = new javax.swing.JRadioButton();
        txtEdad = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        tableEvents = new javax.swing.JScrollPane();
        tabEmpleados = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        brnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameEdad.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameEdad.setText("Edad:");
        jPanel1.add(NameEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, -1));

        Title1.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        Title1.setText("Formulario de Empleado");
        jPanel1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 210, -1));

        NameID1.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameID1.setText("ID:");
        jPanel1.add(NameID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, -1));

        NameNombre.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameNombre.setText("Nombres:");
        jPanel1.add(NameNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        NameApellido.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameApellido.setText("Apellidos:");
        jPanel1.add(NameApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, -1));

        NameCedula.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameCedula.setText("Cedula:");
        jPanel1.add(NameCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, -1));

        NameEstadoC.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameEstadoC.setText("Estado Civil:");
        jPanel1.add(NameEstadoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        NameGenero.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        NameGenero.setText("Genero:");
        jPanel1.add(NameGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        groupEstadoC.add(rdCasado);
        rdCasado.setText("Casado");
        rdCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCasadoActionPerformed(evt);
            }
        });
        jPanel1.add(rdCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        groupEstadoC.add(rdSoltero);
        rdSoltero.setText("Soltero");
        rdSoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSolteroActionPerformed(evt);
            }
        });
        jPanel1.add(rdSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        groupGener.add(rdMasculino);
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rdMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        groupGener.add(rdFemenino);
        rdFemenino.setText("Femenino");
        rdFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemeninoActionPerformed(evt);
            }
        });
        jPanel1.add(rdFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 310, -1));

        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 310, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 310, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 310, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 310, -1));

        tabEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEvents.setViewportView(tabEmpleados);
        tabEmpleados.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(tableEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 300, 260));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        brnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brnLimpiar.setText("Limpiar");
        jPanel1.add(brnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCasadoActionPerformed

    private void rdSolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSolteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSolteroActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasculinoActionPerformed

    private void rdFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFemeninoActionPerformed

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameApellido;
    private javax.swing.JLabel NameCedula;
    private javax.swing.JLabel NameEdad;
    private javax.swing.JLabel NameEstadoC;
    private javax.swing.JLabel NameGenero;
    private javax.swing.JLabel NameID1;
    private javax.swing.JLabel NameNombre;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton brnLimpiar;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup groupEstadoC;
    private javax.swing.ButtonGroup groupGener;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdCasado;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JRadioButton rdSoltero;
    private javax.swing.JTable tabEmpleados;
    private javax.swing.JScrollPane tableEvents;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
